public  class Player {
    public void playing(){

        string player1Name = 'Ali';
        string player2Name = 'Osman';
        string player3Name = 'Hakan';
        string player4Name = 'Murat';
        string player5Name = 'Mehmet';

        system.debug(player1Name);
        system.debug(player2Name);
        system.debug(player3Name);
        system.debug(player4Name);
        system.debug(player5Name);
    }
   
}
